/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RidesImport } from './routes/rides'
import { Route as IndexImport } from './routes/index'
import { Route as RidesIndexImport } from './routes/rides/index'
import { Route as RidesLiveImport } from './routes/rides/live'
import { Route as RidesRideIdImport } from './routes/rides/$rideId'

// Create/Update Routes

const RidesRoute = RidesImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RidesIndexRoute = RidesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RidesRoute,
} as any)

const RidesLiveRoute = RidesLiveImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => RidesRoute,
} as any)

const RidesRideIdRoute = RidesRideIdImport.update({
  id: '/$rideId',
  path: '/$rideId',
  getParentRoute: () => RidesRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/rides': {
      id: '/rides'
      path: '/rides'
      fullPath: '/rides'
      preLoaderRoute: typeof RidesImport
      parentRoute: typeof rootRoute
    }
    '/rides/$rideId': {
      id: '/rides/$rideId'
      path: '/$rideId'
      fullPath: '/rides/$rideId'
      preLoaderRoute: typeof RidesRideIdImport
      parentRoute: typeof RidesImport
    }
    '/rides/live': {
      id: '/rides/live'
      path: '/live'
      fullPath: '/rides/live'
      preLoaderRoute: typeof RidesLiveImport
      parentRoute: typeof RidesImport
    }
    '/rides/': {
      id: '/rides/'
      path: '/'
      fullPath: '/rides/'
      preLoaderRoute: typeof RidesIndexImport
      parentRoute: typeof RidesImport
    }
  }
}

// Create and export the route tree

interface RidesRouteChildren {
  RidesRideIdRoute: typeof RidesRideIdRoute
  RidesLiveRoute: typeof RidesLiveRoute
  RidesIndexRoute: typeof RidesIndexRoute
}

const RidesRouteChildren: RidesRouteChildren = {
  RidesRideIdRoute: RidesRideIdRoute,
  RidesLiveRoute: RidesLiveRoute,
  RidesIndexRoute: RidesIndexRoute,
}

const RidesRouteWithChildren = RidesRoute._addFileChildren(RidesRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rides': typeof RidesRouteWithChildren
  '/rides/$rideId': typeof RidesRideIdRoute
  '/rides/live': typeof RidesLiveRoute
  '/rides/': typeof RidesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rides/$rideId': typeof RidesRideIdRoute
  '/rides/live': typeof RidesLiveRoute
  '/rides': typeof RidesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/rides': typeof RidesRouteWithChildren
  '/rides/$rideId': typeof RidesRideIdRoute
  '/rides/live': typeof RidesLiveRoute
  '/rides/': typeof RidesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rides' | '/rides/$rideId' | '/rides/live' | '/rides/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rides/$rideId' | '/rides/live' | '/rides'
  id: '__root__' | '/' | '/rides' | '/rides/$rideId' | '/rides/live' | '/rides/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RidesRoute: typeof RidesRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RidesRoute: RidesRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/rides"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/rides": {
      "filePath": "rides.tsx",
      "children": [
        "/rides/$rideId",
        "/rides/live",
        "/rides/"
      ]
    },
    "/rides/$rideId": {
      "filePath": "rides/$rideId.tsx",
      "parent": "/rides"
    },
    "/rides/live": {
      "filePath": "rides/live.tsx",
      "parent": "/rides"
    },
    "/rides/": {
      "filePath": "rides/index.tsx",
      "parent": "/rides"
    }
  }
}
ROUTE_MANIFEST_END */
